import "../styles/globals.scss";
import type { AppProps } from "next/app";
import Head from "next/head";

export default function App({ Component, pageProps }: AppProps) {
  return (
    <>
      <Head>
        <title>Online Shopping Site</title>
        <meta name="description" content="Generated by create next app" />
        <link
          rel="icon"
          type="image/png"
          href="https://res.cloudinary.com/dbmumpbin/image/upload/v1669916041/Flipkart/logo.png"
        />
      </Head>
      <Component {...pageProps} />
    </>
  );
}
